name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
    workflow_dispatch:
        inputs:
          solution_name:
            description: 'Solution name to release'
            required: true
            default: 'TestSolution'
          BUILD_ENVIRONMENT_URL:
            description: 'Build environment URL'
            required: true
          PRODUCTION_ENVIRONMENT_URL:
            description: 'Production environment URL'
            required: true
#   release:
#       types: [created]        
permissions:
  contents: write
jobs:
  Release-solution-TestSolution:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: TestSolution
    #   BUILD_ENVIRONMENT_URL: ${{ secrets.BUILD_ENVIRONMENT_URL }}
    #   PRODUCTION_ENVIRONMENT_URL: ${{ secrets.PRODUCTION_ENVIRONMENT_URL }}
    #   BUILD_ENVIRONMENT_URL: ${{ github.event.inputs.BUILD_ENVIRONMENT_URL }}  # Passing the input value for BUILD_ENVIRONMENT_URL
    #   PRODUCTION_ENVIRONMENT_URL: ${{ github.event.inputs.PRODUCTION_ENVIRONMENT_URL }}  # Passing the input value for PRODUCTION_ENVIRONMENT_URL  
    #   #Update your values here
    #   BUILD_ENVIRONMENT_URL: ${{ secrets.BUILD_ENVIRONMENT_URL }}
    #   PRODUCTION_ENVIRONMENT_URL: ${{ secrets.PRODUCTION_ENVIRONMENT_URL}}
    #   CLIENT_ID: ${{ secrets.CLIENT_ID}}
    #   TENANT_ID: ${{ secrets.TENANT_ID}}      
    secrets:
    #   BUILD_ENVIRONMENT_URL: ${{ secrets.BUILD_ENVIRONMENT_URL }}
    #   PRODUCTION_ENVIRONMENT_URL: ${{ secrets.PRODUCTION_ENVIRONMENT_URL}}
      CLIENT_ID: ${{ secrets.CLIENT_ID}}
      TENANT_ID: ${{ secrets.TENANT_ID}}
      envSecret: ${{ secrets.PowerPlatformSPN }}